### ISSUE TITLE
Style the Testimonial Section

### ISSUE THREAD

**Issue by muigaiunaka** [Resilient-Labs/new-view-media#109]

**Comment by muigaiunaka** [comment]
Add min-height of 50vh to testimonials section
``` css
.testimonials {
min-height: 50vh;
}
```

**Comment by muigaiunaka** [comment]
Update testimonial image 
``` css
.testimonial-thumbnail img {
    height: auto;
    width: 100%;
    height: 100%;
    object-fit: cover;
    object-position: top;
}
```
